### ISSUE TITLE
Question: Where should we put the Deliverfile.

### ISSUE THREAD

**Issue by ooikengsiang** [Microsoft/app-store-vsts-extension#102]
I'm trying to use Deliverfile to automate the last part of the submission which is answer the export compliance. I tried many different location, but have no luck getting the fastlane to read the file correctly.
Anyone have any idea where should I place this file exactly?

Thanks.

**Comment by ooikengsiang** [comment]
Add a task to copy Deliverfile to ./fastlane work. Just make sure Deliverfile is in correct format because it doesn't warn you if it didn't read it correctly. Sample of Deliverfile I use is as follow:

```
submission_information({  
  add_id_info_serves_ads: false,
  add_id_info_tracks_action: true,
  add_id_info_tracks_install: true,
  add_id_info_uses_idfa: true,
  export_compliance_app_type: false,
  export_compliance_encryption_updated: false
})
```

Also, I'm using version 2.102.0 of fastlane instead because the latest version currently is broken https://github.com/fastlane/fastlane/issues/13372

**Comment by tipa** [comment]
@ooikengsiang would it be possible to share the copy-task that you had to add in order to make it work?
