### ISSUE TITLE
2 Factor Authentication

### ISSUE THREAD

**Issue by lvandyk** [Microsoft/app-store-vsts-extension#113]
Apple recently enforced 2FA. This is now hanging the release with the following line:

```
Please enter the 6 digit code:
```

I correctly receive the code on my iPhone.

Does anyone have any tips on how to get this working again? I don't mind having to input the code, just don't know whats the best steps to provide the code.

**Comment by madhurig** [comment]
Please setup the fastlane session token as described in the readme: https://github.com/Microsoft/app-store-vsts-extension#two-factor-authentication. We will be updating this guidance since Apple started enforcing 2FA but the steps here should work.

**Comment by madhurig** [comment]
Updated readme for two factor authentication: https://github.com/Microsoft/app-store-vsts-extension/pull/119
