### ISSUE TITLE
Submit MacOS Apps .pkg file submission & not .ipa

### ISSUE THREAD

**Issue by warrenbuckley** [Microsoft/app-store-vsts-extension#116]
Can this extension be modified to support MacOS application submissions please. 💻 

As when creating a package/submission for MacOS as opposed to iPhone/iPad etc you need to upload a .pkg file as opposed to an .ipa 📱

Looking at the source code you set the `-i` param for the FastLane tool
https://github.com/Microsoft/app-store-vsts-extension/blob/master/Tasks/app-store-release/app-store-release.ts#L212

Which means even if I update this tasks `ipaPath` property to be a path to a .app file instead it will not work.

Looking at the source code of FastLane from the link/mention in your own sourcecode it seems FastLane will complain that the file is not an `.ipa` & this gives me no way to upload/submit a .pkg for MacOS review.

Can I suggest that this task supports more options from FastLane to allow not just .ipa submissions

Looks like the setting I would need would be `-c`
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/options.rb#L53-L68

**Comment by madhurig** [comment]
Good suggestion, thank you. We will need to check if -c will work for IPAs or only for macOS pkg files. Based on that we might have to provide an additional input on the task for pkg.

**Comment by warrenbuckley** [comment]
@madhurig I would imagine you would need to update the UI of the task
Like how the **track** dropdown of `production` or `testflight` changes the UI/options available.

Something similar could be done with **platform** to allow you to choose if you are submitting as ios, appletvos or osx
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/options.rb#L77-L85

Where the first two options would use the `-i` switch for an ipa but choosing osx would change the switch to be `-c`

**Comment by warrenbuckley** [comment]
@madhurig I have added a quick PR (not sure if I updated all the right parts, the first time I have looked at code for a VSTS/Azure DevOps task)

https://github.com/Microsoft/app-store-vsts-extension/pull/117
