### ISSUE TITLE
Something wrong with your Export Compliance: "You must provide an answer for this question."

### ISSUE THREAD

**Issue by aruldeepan** [microsoft/app-store-vsts-extension#122]
I am able to upload my .ipa file to appstore. On trying to auto submit the app from review. I get the following error. 

> 'send_app_submission': Something wrong with your Export Compliance: ["You must provide an answer for this question.", "You must provide an answer for this question."

Any solution would be appreciated. I am trying to automate the process in the release pipeline.

**Comment by madhurig** [comment]
You will need to go to your app settings in iTunes and update the "Export Compliance" manually one time.

**Comment by aruldeepan** [comment]
Oh, I see!. Thanks for the info @madhurig. let me try to do that and let you know further

**Comment by aruldeepan** [comment]
Hi Madhurig, The solutions worked fine. I am able to upload the artifact and auto submit the app for app store review. However, I am facing 2 strange issues now.

1.  While my app is getting uploaded and app store is processing the build. I get the following message in the task output. However, even after I get an error email message from the app store. The task output still says the following message and it keeps running more than an hour. Not sure if it is already reproduced. I have to manually cancel the release pipeline.

> Waiting App Store Connect processing for build 4.7.190415 (7872)... this might take a while...

2. While I manually upload my build to the app store. I am able to get a successful upload. However, While I upload using our extension. App store rejects the app saying the following reason. Did you face this issue before?

> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data.

Appreciate your help again!. Thanks in advance.

**Comment by madhurig** [comment]
I haven't seen this but looks like you need to update the Info.plist for the 2nd issue. For the 1st issue, if you don't want to wait for processing, there is an option on the task you can use to skip waiting.

**Comment by arul-deepan** [comment]
Thank you for the inputs @madhurig . Will try this and let you know for any queries.

**Comment by aruldeepan** [comment]
Thanks for the inputs @madhurig. Will try this out and let you for any queries.

**Comment by anatolybolshakov** [comment]
Hi @aruldeepan, is this issue still actual for you?

**Comment by anatolybolshakov** [comment]
HI @aruldeepan, please let me know if it is still actual for you

**Comment by egor-bryzgalov** [comment]
Hi, @aruldeepan! I'm closing this issue. Please feel free to reopen it if it's still relevant for you
