### ISSUE TITLE
Problem accessing /v2/providers/-/apps/-/platforms/ios/trains. Reason: Gone

### ISSUE THREAD

**Issue by jcravioto** [microsoft/app-store-vsts-extension#123]
Hi, 
My team has been using this extension for some time now, and it's been tremendously helpful. Just last week we started getting a new error when we submit a new version to testflight. We use the release task to upload to test flight and we let a build run through the whole processing wait so we are aware on when it's over. 
Lately the failure has appear when the package is uploaded and the waiting is about to begin. The error that I'm getting is:

/Users/vsts/.gem-cache/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/client.rb:321:in `handle_response': [!] <html> (Spaceship::UnexpectedResponse)

<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/80423/apps/477537958/platforms/ios/trains. Reason:
<pre>    Gone</pre></p>
</body>
</html>
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/client.rb:31:in `get_build_trains'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/build_trains.rb:16:in `all'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/build.rb:110:in `all'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/build.rb:121:in `all_processing_builds'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/fastlane_core/lib/fastlane_core/build_watcher.rb:38:in `watching_build'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/fastlane_core/lib/fastlane_core/build_watcher.rb:12:in `wait_for_build_processing_to_be_complete'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/pilot/lib/pilot/build_manager.rb:61:in `wait_for_build_processing_to_be_complete'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/pilot/lib/pilot/build_manager.rb:53:in `upload'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/pilot/lib/pilot/commands_generator.rb:66:in `block (2 levels) in run'
from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
from /Users/vsts/.gem-cache/gems/fastlane-2.119.0/bin/fastlane:23:in `<top (required)>'
from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>' 

From the error it seems like fastlane is not able to find the iOS/trains, but the way that we are doing our submissions hasn't changed. Would this be something new?

**Comment by madhurig** [comment]
Seems like issue https://github.com/fastlane/fastlane/issues/14521

**Comment by joshdholtz** [comment]
This is fixed in https://github.com/fastlane/fastlane/pull/14523 and released in version [2.120.0](https://github.com/fastlane/fastlane/releases/tag/2.120.0) of fastlane 💪

**Comment by anatolybolshakov** [comment]
Thanks @joshdholtz! @jcravioto is this issue still actual for you?

**Comment by anatolybolshakov** [comment]
Hi @joshdholtz, @jcravioto please let me know if it is still actual for you

**Comment by egor-bryzgalov** [comment]
Hi @joshdholtz, @jcravioto. Closing this issue. Please feel free to reopen it if it's still relevant for you
