### ISSUE TITLE
Add option to select Xcode version

### ISSUE THREAD

**Issue by naeemshaikh90** [microsoft/app-store-vsts-extension#124]
There should be an option to select default Xcode version for Azure DevOps Extension for the Apple App Store

Lots of other users are also facing issues when Xcode version changes: #105 

Current solution to add a command line code to select default Xcode version:
```
echo "before: "
xcodebuild -version
echo "Set Default Xcode version"
sudo xcode-select --switch /Applications/Xcode_10.1.app
echo "after: "
xcodebuild -version
```

![Screen Shot 2019-04-11 at 12 39 12 PM](https://user-images.githubusercontent.com/10736853/55937682-386ba680-5c57-11e9-8310-5face9713a75.png)
![Screen Shot 2019-04-11 at 12 37 54 PM](https://user-images.githubusercontent.com/10736853/55937699-40c3e180-5c57-11e9-9a36-f662c853fe89.png)

**Comment by madhurig** [comment]
Thanks for the feedback. We are considering having a task like "Use Xcode version" to allow the version to be persisted across multiple tasks or scripts that you run after it. It is on our backlog but we don't have an ETA yet.

**Comment by naeemshaikh90** [comment]
Thanks for the quick reply, let me know if I can help you anyway.

**Comment by naeemshaikh90** [comment]
@madhurig Any updates on this?

**Comment by anatolybolshakov** [comment]
Hi @naeemshaikh90, we are going to pick it up in the near future, but please feel free to contribute if you have any suggestions!

**Comment by anatolybolshakov** [comment]
@naeemshaikh90 @markdou812 this feature was postponed due to more prioritized tickets. We can't give right estimation at the moment, but going to return back to this once we have capacity.
Please feel free to contribute if you have some suggestion around this enhancement.

**Comment by denis-tikhomirov** [comment]
Hello @naeemshaikh90, @markdou812,
Really it doesn't look as correct way to add new task to select specific version of Xcode to App Store extension repo. But this task can be added to [Azure Pipeline Tasks repo](https://github.com/microsoft/azure-pipelines-tasks). Please create feature request (voting ticket) for creation of UseXcodeVersion task in [VS Developer Community](https://developercommunity.visualstudio.com/report?space=21&entry=suggestion).

**Comment by alexander-smolyakov** [comment]
Hey @naeemshaikh90, @markdou812, we believe that the best approach will be creating a separate pipeline task to provide a possibility to change Xcode version during pipeline execution and we believe that such task should be presented in the [default collection of pipelines tasks](https://github.com/microsoft/azure-pipelines-tasks) (Such as [UsePythonVersionV0](https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/UsePythonVersionV0) pipeline task) not in the extension itself. However, to proceed with the task implementation, we need to see if such a task will be in demand by Azure DevOps users. Thus, could you please create a feature request (voting ticket) regarding implementation of `UseXcodeVersion` task in [VS. Developer Community](https://developercommunity.visualstudio.com/report?space=21&entry=suggestion)?

With that being said, let me close this ticket. Feel free to request a reopening if you have any further questions.
