### ISSUE TITLE
Can we use windows machine for deployment

### ISSUE THREAD

**Issue by deepak10** [Microsoft/app-store-vsts-extension#125]
Our build server hosted on the windows machine. Can we use the same machine for app release using FastLane? or Can we use App Store Release on a windows machine?

**Comment by madhurig** [comment]
Apple does not support uploading from a windows machine, so App Store Release cannot run on a windows machine, a Mac is required.

**Comment by deepak10** [comment]
So it means my build server has to mac machine right? what if I will pass .ipa file to App Store Release? Does it work on windows machine if I pass the .ipa using file path instead of building the ios application?

**Comment by madhurig** [comment]
Apple does not support uploading .ipa files from a windows machine - both build and upload to AppStore have to done on a macOS machine only. You cannot use the App Store Release task on a windows machine.

**Comment by deepak10** [comment]
Thanks for the information. I am able to upload .ipa in Testflight. But I have facing one issue. I am getting below error

**Build doesn't show up in the build list anymore, waiting for it to appear again (check your email for processing issues if this continues)**

Earlier I was getting this error for encryption compliance but after adding key in info.plist that is solved in iTunes but in pipeline, I am still getting  above error

**Comment by deepak10** [comment]
Along with the above error, I am also not able to update **what to test** string in iTunes Testflight.

**Comment by madhurig** [comment]
Did you select 'Skip Build Processing Wait' ? That might be why **what to test** is not getting updated. If you continue seeing errors with the IPA not listing, there is something you need to update in your app settings.

**Comment by deepak10** [comment]
No, I haven't selected Skip Build Processing Wait'option. And for IPA not listing, I checked in the iTunes build is already processed without any issue. Can u help me on this? One more thing I am deploying build on TestFlight.

**Comment by deepak10** [comment]
Along with the above issue, I am also not able to set External tester in TestFlight

**Comment by deepak10** [comment]
any update/suggestion on this.
