### ISSUE TITLE
How to generate fastlane session on Hosted MacOS agent 

### ISSUE THREAD

**Issue by vkalokhe** [microsoft/app-store-vsts-extension#128]
As I am trying to add apple app store extension to create service connecting.

but not able to generate fastlane session on Hosted MacOS agent

Need to help on the procedure to generate the fastlane session on Hosted agent.

**Comment by tidusjar** [comment]
I also have this issue, hoping for an update

**Comment by madhurig** [comment]
Please follow the [instructions here](https://github.com/microsoft/app-store-vsts-extension#two-factor-authentication) to create a fastlane session token on your local mac and set the token you generated in the `Apple App Store` service connection.

**Comment by tidusjar** [comment]
Is there no way to generate the session token as part of the build pipeline?

Since the session token has a limited TTL, it makes sense to be able to generate a new token as part of the build pipeline and then use that new token.

**Comment by madhurig** [comment]
Session token needs interactive login (2FA) which is not possible on the hosted VMs.

**Comment by anatolybolshakov** [comment]
Hi @tidusjar, is this issue still actual for you?

**Comment by AvaJV** [comment]
I am also experiencing the same issue.
As I am using the Hosted MacOS agent it would be good that there is a way to automate this, as I am myself using a Windows Machine which makes it hard to get the fastlane token (in the right region).
Therefore my question is: Are there any timelines for getting a generated fastlane session ID on the hosted MacOS agent?

Or can we work around this as we already have a App specific password.

**Comment by alexander-smolyakov** [comment]
There's no appropriate way to implement this for now since you need to pass 2FA to generate a Fastlane session anyway.  It's not possible on the hosted VMs at the moment.  

So closing it, if you still have some questions feel free to reopen it.

Thanks!
