### ISSUE TITLE
Meta data path in App Store Promote

### ISSUE THREAD

**Issue by ulyssetsd** [microsoft/app-store-vsts-extension#129]
### Use case
- using the Release task to deploy to TestFlight track
- using the Promote task to promote from TestFlight track to production track

### Issue
In the release task, if you choose "production track" you can specify the metadata file path but not if you choose the "TestFlight track".

I can't promote the app from TestFlight to production because the release notes are missing (because there is no metadata). After looking on the fastlane doc, I try to add `release_notes: "my notes"` in the Additional fastlane arguments but it didn't work.

### Questions
- Is there a simple way to specify the release_notes in the promote track ?
- Is is possible to add the **Upload Metadata** _(Checkbox)_ and **Metadata Path** _(File path)_ in the promote task ?

**Comment by ThomasNigro** [comment]
+1 without the option to update the release notes from the Release pipeline, there's not much we can do :(

**Comment by jonsamwell** [comment]
Agree we should be able to upload the metadata and screenshot even if we are not promoting to the production track

**Comment by jonsamwell** [comment]
@ulyssetsd This should work now there was an issue that has been fixed now that was parsing the additional fastlane arguments incorrectly.  Also you could just check the 'Skip binary upload' checkbox in the task to just upload the metadata.

**Comment by ulyssetsd** [comment]
@jonsamwell Thank you very much, I saw that you fix the additional fastlane arguments ! Using `release_notes: "my notes"` in the Additional fastlane arguments should work now

**Comment by jonsamwell** [comment]
@ulyssetsd no problem 👍
