### ISSUE TITLE
Promote build with metadata

### ISSUE THREAD

**Issue by SmutsMuts** [microsoft/app-store-vsts-extension#142]
Hello,

So I've added a release pipeline which has several steps, the first step is to release to test flight so our beta testers can test the app and then approve it. Then the step after that which the beta testers needs to approve before it starts is to release to production. First I added a step using the release task and selected Production instead of Test flight, but after I ran this step it failed because the build is aleady uploaded to store and cannot be uploaded several times. So, nice I though, then I am supposed to use the promote task instead, but how do I get the fastlane metadata settings in the promote task that I have in the release task? Otherwise I won't get release notes and other things in a nice way, and it feels wrong to increase the build number and upload a new build, I want to release the exact same build that the beta testers approved...

Any ideas around this?

**Comment by tipa** [comment]
Having the exact same problem. The Promote task always adds "skip_metadata false" which makes it impossible to add them on the Promoting task

**Comment by Tofalvy** [comment]
Same problem for me.
Any update on this?

**Comment by SmutsMuts** [comment]
Forgot to do an update on this, but yes, they have solved this issue. When you release to production you can check the "Skip Binary Upload" checkbox and then it will just use the build that you uploaded in the previous step when you uploaded for Test Flight. 
Right now I have another issue instead that when you upload for TestFlight it wants to have some contact information and I have provided that in fastlane but it doesn't seem to care about that, haven't done a release in a while now so might be fixed, seems like they at least fix things relatively fast for the connections to google and apple.

**Comment by anatolybolshakov** [comment]
Hi @SmutsMuts is this issue still actual for you?

**Comment by SmutsMuts** [comment]
Nope this is not an issue any more. Now I have a different issue but I will check if someone else have a solution or create a new thread for that.
