### ISSUE TITLE
Not able to submit beta_app_review_info argument

### ISSUE THREAD

**Issue by NaveenArasu** [microsoft/app-store-vsts-extension#150]
I am missing the syntax to submit the 'beta_app_review_info' details through Additional fastlane arguments. 

The argument has child elements, and I tried few syntaxes, but they didnt work. 

Information to be added
beta_app_review_info: {
    contact_email: "email@email.com",
    contact_first_name: "Connect",
    contact_last_name: "API",
    contact_phone: "5558675309",
    demo_account_name: "demo@email.com",
    demo_account_password: "connectapi",
    notes: "this is review note for the reviewer <3 thank you for reviewing"
  },

Syntax that I tried and which didnt work: 

fastlaneArguments: --contact_email:"email@email.com" --contact_first_name:"Connect" --contact_last_name:"API" --contact_phone:"5558675309" --demo_account_name:"demo@email.com" --demo_account_password:"connectapi" --notes:""

fastlaneArguments: --beta_app_review_info contact_email:"email@email.com",contact_first_name:"Connect",contact_last_name:"API",contact_phone:"5558675309",demo_account_name:"demo@email.com",demo_account_password:"connectapi",notes:""

**Comment by 1Siger1** [comment]
Fastlane had a problem lately with setting this values. There was issue which was resolved (issue is located [here](https://github.com/fastlane/fastlane/issues/16294), but it solves the problem for fastlane users and not for the Azure DevOps task users. From what I read in this fastlane thread there is no way for now to set those values using additional arguments in fastlane. To solve the problem we need to set **beta_app_review_info** details in Fastfile which I think is generated by the this task.

**Comment by kitolog** [comment]
As I got it right,  it should be possible to set env variable in Azure DevOps pipeline variable like this:
PILOT_BETA_APP_REVIEW_INFO='{"contact_first_name":"...",...}'

**Comment by 1Siger1** [comment]
To do that without adding the variable (I used this in task group and did not want to pass it as variable) in can be set using smal Powershell step with inline code:
`$PILOT_BETA_APP_REVIEW_INFO = '{"contact_email":"#########","contact_first_name":"#########","contact_last_name":"#########","contact_phone":"#########"}'
Write-Host "##vso[task.setvariable variable=PILOT_BETA_APP_REVIEW_INFO]$PILOT_BETA_APP_REVIEW_INFO"
`
@thecivillain thank you for the suggestion.

**Comment by anton-erofeev** [comment]
Hi, @NaveenArasu 
Is this issue still actual for you?

**Comment by NaveenArasu** [comment]
> Hi, @NaveenArasu
> Is this issue still actual for you?

The issue is resolved now.Thanks.

**Comment by anton-erofeev** [comment]
@NaveenArasu 
Closed since the issue is resolved. Please feel free to reopen it.
