### ISSUE TITLE
Using a NON 2FA account with fastlane version 2.150.0+ won't login

### ISSUE THREAD

**Issue by valdetero** [microsoft/app-store-vsts-extension#155]
I have an apple account created before the mandated 2FA just for uploading builds. (I'd like to leave it that way) Everything worked fine a few days ago and then this task started reporting the error `ERROR: Your account information was entered incorrectly. (-20101)`. The only thing that changed is the Azure Devops agent was using a newer version of fastlane. I double checked the username / password (which hasn't changed as was still correct) and I switched from Service Connection to plain username / password. None of that fixed the issue. I downgraded / "pinned" the fastlane to version 2.149.1 (which worked a couple of days ago) and it finally uploaded. 
[Fastlane 2.150.0](https://github.com/fastlane/fastlane/releases/tag/2.150.0) is using Apple's new App Store Connect API.

**Comment by egor-bryzgalov** [comment]
Hi, @valdetero 

Could you please confirm that this issue is still relevant for you. Have you tried the latest version of Fastlane?
We're looking forward to hearing from you!

**Comment by valdetero** [comment]
@egor-bryzgalov It looks like it might be fixed in the latest version of fastlane - 2.157.4. I have a different app with a different NON 2FA account and it was successfully able to login to iTunes Connect last week. I'll close this and either re-open or create a new one if it comes back. Thank you.
