### ISSUE TITLE
Stuck in Publish to Testflight

### ISSUE THREAD

**Issue by jsabacinski** [microsoft/app-store-vsts-extension#156]
I'm trying to set up a release pipeline fot my iOS app, so I don't have to manually deploy it to Testflight. It doesn't work though... It gets the .ipa file from build pipeline artifacts, starts the "Publish to Testflight" task and it looks well, but it stucks then and in output you can see just some garbage:

Successfully installed fastlane-2.152.0
Parsing documentation for fastlane-2.152.0
Installing ri documentation for fastlane-2.152.0
Done installing documentation for fastlane after 87 seconds
1 gem installed
[command]/usr/local/opt/ruby/bin/gem update fastlane -i /Users/runner/.gem-cache
Updating installed gems
Nothing to update

and then it goes like this for even several hours, till I manually cancel it:

�g�����p|3O�$i��R�ˋ%��{�8�^�x�&k|\����iR����?WK玆Hs�G��?��5�cZ�sBg���CO�<g�mȋ7eD�"=�=T�%�39���i�����h��z�hY�(~6u~�`�)g�nA����x>��H-���gJ���S�W��-�PcfS��R��V�.��}x�6�����ƸLЈ�.
���A��!4��m�&Y-��}���/����c���ţ���	g%�����D6����_!����=#<��)��a<?�a��e�����>��i���_���U<Q�������i�j���?��r:��rt�𛜻@W/<�N6�|�gبgɞ�^�b�����g>����S��}u���c��)�n0��������t*m�'�������z�{cT���Ԅ:w��u�ӄ:��/�$m�먿�ۮX3K�Ln�e[J�C��}Ck=�1:�Ӿ�

Has someone experienced it? What could I do? Have I missed something?

**Comment by anatolybolshakov** [comment]
Hi @jsabacinski is it still actual for you? Could you please provide pipeline yaml file also?

**Comment by anatolybolshakov** [comment]
Hi @jsabacinski ping 😃 please let us know if it's still actual for you

**Comment by jsabacinski** [comment]
> Hi @jsabacinski ping 😃 please let us know if it's still actual for you

Sorry, I have totally missed your reply. I know, I could solve this problem, but I don't remember how... It was helpful though, to download and analyse the logs of failed buid. For me you can close the issue. 

Cheers!

**Comment by anatolybolshakov** [comment]
@jsabacinski ok, thanks! I'm closing it currently
