### ISSUE TITLE
App Store Release task uses presence of appSpecificPassword to imply fastlaneSession is required and fails if not present.

### ISSUE THREAD

**Issue by GregHNZ** [microsoft/app-store-vsts-extension#165]
If an app specific password is provided, the app-store-release task turns on isTwoFactorAuthEnabled = true, then fails if the fastLaneSession variable is not present.

However the fastlane documentation says that for uploading applications, you can use either spaceauth or an app specific password. 

It says that if you want to do anything _other_ than uploading a file, then spaceauth is required.

https://docs.fastlane.tools/best-practices/continuous-integration/#separate-apple-id-for-ci
Quote:

> Application specific passwords
> 
> If you want to upload builds to App Store Connect (actions upload_to_app_store and deliver) or TestFlight (actions upload_to_testflight, pilot or testflight) from your CI machine, you need to generate an application specific password:
> 
>     Visit appleid.apple.com/account/manage
>     Generate a new application specific password
>     Provide the application specific password using the environment variable FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
> 
> This will supply the application specific password to iTMSTransporter, the tool used by those actions to perform the upload.
> 
> Note: The application specific password will not work if your action usage does anything else than uploading the binary, e.g. updating any metadata like setting release notes or distributing to testers, etc.
> 
> spaceauth
> 
> All other actions interacting with Apple's APIs do not accept application specific passwords.
> 

This seems pretty clear that for just uploading the file the fastlane session variable is not required.

**Comment by sdobrodeev** [comment]
Hi @GregHNZ We tried to fix this behavior in the attached PR. But it didn't work. It seems that it still requires fastlane session - even if we are trying to upload only binary file. If you have a working solution - please contribute it.

**Comment by sdobrodeev** [comment]
Hi @GregHNZ Is this problem still actual for you?

**Comment by sdobrodeev** [comment]
Closed due to inactivity. Please feel free to reopen it if the problem is still relevant.
