### ISSUE TITLE
Skip Binary Upload still requires path to the .ipa

### ISSUE THREAD

**Issue by JohnHDev** [microsoft/app-store-vsts-extension#174]
How can I deploy screenshots and release note metadata without needing an ipa? I have separate pipelines for these tasks, and I don't want to have to build the ipa just to get to deploy screenshots and release notes.

**Comment by anatolybolshakov** [comment]
Hi @JohnHDev thanks! We are going to prepare a fix for this issue

**Comment by anatolybolshakov** [comment]
Closing it since related changes has been released
