### ISSUE TITLE
Does App Store Promote work for automatically releasing an app that has already been approved?

### ISSUE THREAD

**Issue by rohanp-91** [microsoft/app-store-vsts-extension#222]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: App Store Promote  

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted agent (internal 

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

>Not sure if above is necessary as this is just a question

## Issue Description

**Question**: 

Our release pipeline setup is as below:

Full Test Pass -> Upload to TestFlight and Submit for Review in PROD with **release automatically unchecked** (these two triggered in parallel) -> Promote to PROD

In the last **Promote to PROD** step, I want to use the App Store Promote ADO task and want to release the version that was previously submitted for review (might be at approved stage at this time as I am planning to trigger this task manually later). My question is whether the App Store Promote task, with **release automatically** selected, will work in releasing the already approved latest version to PROD or does it **only** work in promoting from TestFlight to PROD? 

Please let me know if you need more information.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

N/A

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

N/A

**Comment by alexander-smolyakov** [comment]
Hey @rohanp-91, the Apple Promote task designed only to promote build from TestFlight to Production, and most likely the scenario you describe will not work.

However, if you need this functionality in the task, could you create a feature request for it and describe in more detail how you see this feature should work?

**Comment by rohanp-91** [comment]
Hi @alexander-smolyakov, 

Thanks for the response. I have opened feature request #225. Please let me know if I need to add any additional information in the feature request. Also, please feel free to drop me an email or ping me on Teams in case you have any questions. My alias is ropathak.

As of now, I am **closing** this issue. The requirement can be tracked in the feature request. Thanks!
