### ISSUE TITLE
Setting shouldAutoRelease to false does not work correctly

### ISSUE THREAD

**Issue by Mosc** [microsoft/app-store-vsts-extension#235]
## Required Information

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Apple App Store Release

## Environment
- Server - Azure Pipelines
- Agent - Hosted

## Issue Description

When `shouldAutoRelease` is set to `false`, the task does not provide the `automatic_release` argument to fastlane, even though fastlane does expect either the automatic release or auto release date argument to be set. Given that the Apple App Store Release task does not offer setting an auto release date, it should always set the `automatic_release` argument to either `true` or `false`.

### Error logs

Release type will not be set because neither `automatic_release` nor `auto_release_date` were provided. Please explicitly set one of these options if you need a release type set

**Comment by DaniilShmelev** [comment]
Hey @Mosc! We've fixed the issue and the related changes have been deployed.
