### ISSUE TITLE
Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues) and I noticed that the version uploaded but not submitted to review 

### ISSUE THREAD

**Issue by Mahmoud-Bassuni** [microsoft/app-store-vsts-extension#261]
## Note  
Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)

its seem to appstore but I can't make submit to review
- task: AppStoreRelease@1
    inputs:
      serviceEndpoint: 'AppStore Connect'
      releaseTrack: 'Production'
      appIdentifier: 'Com.xyz'
      appType: 'iOS'
      ipaPath: '$xyz.ipa'
      uploadMetadata: true
      metadataPath: '$(Build.ArtifactStagingDirectory)/metadata'
      shouldSubmitForReview: true
      shouldAutoRelease: false
      shouldSkipWaitingForProcessing: false
      shouldSkipSubmission: false
      appSpecificId: '1462899730'
      fastlaneArguments: '-z "$(appVersionNo)" --submission_information "{\"add_id_info_uses_idfa\": false , \"export_compliance_uses_encryption\": false}"'

**Comment by anatolybolshakov** [comment]
Hi @Mahmoud-Bassuni  this is expected since build submission could take some time to be done - you can use 'shouldSkipWaitingForProcessing' input - to skip waiting for the finishing of this process.

**Comment by Mahmoud-Bassuni** [comment]
so that mean I will upload build and submit for review incase  shouldSkipWaitingForProcessing = true

**Comment by Mahmoud-Bassuni** [comment]
Actually its worked for me 2 month ago with shouldSkipWaitingForProcessing = false I don't know what happened @anatolybolshakov

**Comment by anatolybolshakov** [comment]
@Mahmoud-Bassuni time for build processing could vary for because of different factors - for this case I would suggest to reach out to apple support - if you experience some increased delay for the processing on apple side.

**Comment by Mahmoud-Bassuni** [comment]
actually the build upload on apple and I can't submit for review every time got Waiting for the build to show up in the build list  until the pipeline timeout

**Comment by anatolybolshakov** [comment]
@Mahmoud-Bassuni this issue is not related to the task itself - please reach out to Apple support for further help. If you suspect that there is some issue with fastlane tools which task is using - you can also open an issue https://github.com/fastlane/fastlane for further troubleshooting.

**Comment by anatolybolshakov** [comment]
Closing it at the moment since it's not related to the issue with task itself - please feel free to ask any further questions.
