### ISSUE TITLE
Apple App Store (TestFlight Track) task failed with Transporter Error 1272

### ISSUE THREAD

**Issue by JoyFang1113** [microsoft/app-store-vsts-extension#262]
## Note  
Since earlier this month, our CI/CD pipeline (using ADO extension Apple App Store) are not able to upload builds to Testflight with a transporter error "An error occurred while trying to call the requested method validateAssets. (1272)", and it seemed like a broad issue from Apple's side, (please see this post: https://github.com/fastlane/fastlane/issues/19572), which was fixed yesterday, but the issue when using this ADO extension still presents.

## Required Information
this is the configuration in the task
![image](https://user-images.githubusercontent.com/32690264/141388307-b240303c-e32e-4c09-a3a1-8b1af3d426f3.png)

this is the error log
![image](https://user-images.githubusercontent.com/32690264/141388651-b879ab4c-2584-4920-8a75-df5c0f39d891.png)

**Question, Bug, or Feature?**  
*Type*: bug

**Enter Task Name**: Apple App Store Release

## Environment
- Server - Azure Pipelines
   https://office.visualstudio.com/CLE/_releaseDefinition?definitionId=939&_a=environments-editor-preview
https://office.visualstudio.com/CLE/_releaseProgress?_a=release-pipeline-progress&releaseId=396711

- Agent - Hosted
Azure Pipeline

## Issue Description
With the fastlane issue fixed from Apple side, this Microsoft owned ADO vsts extension still failed with the Transporter validateAssets 1272 error. This is blocking all our iOS and Mac apps uploading to Apple store.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
[tasklog_10.log](https://github.com/microsoft/app-store-vsts-extension/files/7524065/tasklog_10.log)

**Comment by anatolybolshakov** [comment]
Hi @JoyFang1113 this seems to be related to the fastlane issue which is still active - https://github.com/fastlane/fastlane/issues/19572 - please reach out to fastlane support for more details.

**Comment by idelfonsog2** [comment]
@JoyFang1113 any update on this since the [fastlane/issues/19572](https://github.com/fastlane/fastlane/issues/19572) is closed already? I only ask cause... you know... I'm having the same issue🥁

**Comment by anatolybolshakov** [comment]
@idelfosog2 @JoyFang1113 since the fix for this issue was shipped with fastlane 2.198.0 - you can specify this version by 'installFastlane' and 'fastlaneToolsVersion' inputs.
Closing this one at the moment as external - please ping if you have any further questions.
