### ISSUE TITLE
Submit for Review fails with "Version is not ready to be submitted yet"

### ISSUE THREAD

**Issue by rohanp-91** [microsoft/app-store-vsts-extension#271]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Apple App Store Release  

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

Using ADO task in Azure Release Pipelines.
Team: Bing Ads Mobile
Link to release: https://msasg.visualstudio.com/Bing_Ads/_releaseProgress?_a=release-pipeline-progress&releaseId=1162051

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Azure Pipelines | internal-macos-10.15

## Issue Description

Submit for review using Apple App Store Release task failing with below error:

2022-02-04T03:00:28.0332510Z /Users/runner/.gem-cache/gems/fastlane-2.204.2/spaceship/lib/spaceship/connect_api/api_client.rb:199:in `handle_response': [!] appStoreVersions with id 'e0207fc5-203a-4902-9f63-9abeffcb29e1' is not in valid state. - This resource cannot be reviewed, please check associated errors to see why. (Spaceship::UnexpectedResponse)
2022-02-04T03:00:28.0335240Z The request cannot be fulfilled because of the state of another resource. - Version is not ready to be submitted yet, please try again later.
 
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/13272298/157798915-e626161e-9a47-4f99-82f4-fad20841f4a3.png">

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by anatolybolshakov** [comment]
Hi @rohanp-91 this error seems to come from fastlane - I would suggest to refer the comments from https://github.com/fastlane/fastlane/issues/17933 and see if it helps.

**Comment by rohanp-91** [comment]
The above issue is similar to ours but not the same issue. In the above issue it fails with below:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/13272298/158431046-6f9ddf21-be5f-4ed3-88c7-f6beb48c63e1.png">

In our case, there are no such errors and the error message is also different - 'Version not ready to be submitted yet'. I have opened an issue on fastlane's github page, but I'd like to keep this open till a resolution is found. Other teams within MSFT are also seeing similar issues using the ADO task.

**Comment by DenisRumyantsev** [comment]
@rohanp-91 could you try to run the pipeline using `2.199.0` and `2.204.2` Fastlane versions in the `Submit App For Review` step?

**Comment by rohanp-91** [comment]
There is a bug in the ADO task where, if you specify a particular fastlane version, it fails to uninstall the latest fastlane version and ends up using the latest one (even though it installs the specified version). But I can retry with 2.199.0.

**Comment by anatolybolshakov** [comment]
@rohanp-91 the task is trying to uninstall all fastlane versions before installing of the specific version, and if there is the latest already installed - will use it even if specific version was installed.
Do you see some specific error when task is trying to uninstall existing fastlane versions?

**Comment by anatolybolshakov** [comment]
Hi @rohanp-91 do you have any updates?

**Comment by DenisRumyantsev** [comment]
Hi @rohanp-91, any updates about this issue? Could you try to use `2.199.0` and `2.204.2` Fastlane versions as was suggested?

**Comment by DenisRumyantsev** [comment]
Hi @rohanp-91, I am closing this issue for now. Feel free to reopen it if it will be needed.
