### ISSUE TITLE
Azure Devops to Deploy IOS Application on Test-flight

### ISSUE THREAD

**Issue by madcwb** [microsoft/app-store-vsts-extension#274]
I am using ["Azure DevOps Extension for the Apple App Store"](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store) to publish my app

But in process return error "/Users/runner/.gem-cache/gems/fastlane-2.205.2/spaceship/lib/spaceship/connect_api/token.rb:71:in `initialize': [!] string contains null byte (ArgumentError)"
and I cant find the reason.

I need help to identify the reason.

See details

![Screenshot_5](https://user-images.githubusercontent.com/11164036/165591382-7cacd9f1-8331-49e4-8789-163a3c0e4b88.png)
![Screenshot_6](https://user-images.githubusercontent.com/11164036/165591392-768c3e5c-79ef-4d85-b8bd-c6f14228426d.png)

**Comment by GarikProg** [comment]
Hi @madcwb  thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by Kozlov-Igor** [comment]
Hi @madcwb  thanks for reporting! We are working on more prioritized issues at the moment, but will get back to this one soon.

**Comment by legrignotin** [comment]
@madcwb If you still have the issue, you need to covert your apiToken to a base64 string and it should work :)

**Comment by max-zaytsev** [comment]
Looks like an encoding problem
