### ISSUE TITLE
Unable to deploy to TestFlight with Token based authentication

### ISSUE THREAD

**Issue by ogezue** [microsoft/app-store-vsts-extension#277]
**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: Unable to deploy to TestFlight with Token based authentication  

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

## Environment
Azure Pipelines

## Issue Description

I'm unable to use AppStoreRelease to publish the app to my external testers. Before I used AppCenter without a problem.
Here is the script I'm currently using. It complains about a missing fastlane session and I don't know if I really need to provide it and how. Currently I'm using installFastle false

- task: AppStoreRelease@1
  displayName: 'Publish to the App Store TestFlight track'
  inputs:
    serviceEndpoint: 'app-store-connection'
    releaseTrack: 'TestFlight'
    appIdentifier: 'my.identifier.com'
    appType: 'iOS'
    ipaPath: '$(build.artifactstagingdirectory)/**/*.ipa'
    shouldSkipWaitingForProcessing: false
    distributedToExternalTesters: true
    externalTestersGroups: 'My Team'
    appSpecificId: '1234567890'
    installFastlane: false
    releaseNotes: '$(build.artifactStagingDirectory)/releaseNotes.txt'
### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
I tried several options. If I don't provide release nots (which I copy from the repo without an error in a previous step) it complains that it can't deploy to testers without it. With release Notes it complains about the missing session. 

### Error logs

	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/pilot/lib/pilot/commands_generator.rb:167:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/pilot/lib/pilot/commands_generator.rb:19:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `<main>'
/usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/token.rb:71:in `initialize': string contains null byte (ArgumentError)
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/token.rb:71:in `new'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/token.rb:71:in `create'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/token.rb:49:in `from_json_file'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/spaceship/lib/spaceship/connect_api/token.rb:33:in `from'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/pilot/lib/pilot/manager.rb:23:in `login'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/pilot/lib/pilot/manager.rb:19:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/pilot/lib/pilot/build_manager.rb:17:in `upload'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/pilot/lib/pilot/commands_generator.rb:67:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/pilot/lib/pilot/commands_generator.rb:167:in `run'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/pilot/lib/pilot/commands_generator.rb:19:in `start'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/fastlane/lib/fastlane/cli_tools_distributor.rb:115:in `take_off'
	from /usr/local/lib/ruby/gems/2.7.0/gems/fastlane-2.206.2/bin/fastlane:23:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `load'
	from /usr/local/lib/ruby/gems/2.7.0/bin/fastlane:25:in `<main>'
##[error]Error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/fastlane' failed with exit code 1
Finishing: Publish to the App Store TestFlight track

**Comment by max-zaytsev** [comment]
@ogezue Thanks for reporting! We are working on more prioritized issues now but will get back to this one soon

**Comment by pk1498** [comment]
Hi @ogezue, were you able to resolve this? I am facing the same error. I have double checked my service endpoint credentials and also tried token-based authentication, but this error is consistent.

@max-zaytsev can you please look into this, thank you.

**Comment by ogezue** [comment]
@pk1498 Yes, I did. Problem was that my token for Apple was not base64 encoded. The error message doesn't make this clear.

**Comment by Debdan1997** [comment]
Base64 encoding isn't working for me, I'm trying with encoding -----BEGIN PRIVATE KEY-----\nxxxxyyyyzzzz\n-----END PRIVATE KEY-----, sometimes getting `initialize': [!] string contains null byte and often `initialize': [!] invalid curve name (OpenSSL::PKey::ECError) error. When we tried to run fastlane locally via using json file containing the api key authentication succeded. Kindly help with the encoding. I don't have the .p8 file as it was supplied via keyvault as a string secret.
Thanks
