### ISSUE TITLE
Got an email "Action required: Transition from XML to App Store Connect API"

### ISSUE THREAD

**Issue by 404pilot** [microsoft/app-store-vsts-extension#284]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: `AppStoreRelease `

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

----
The task works! But we received an email from Apple
```
subject: Action required: Transition from XML to App Store Connect API

We noticed that you recently used the XML feed to manage and deliver content to App Store Connect. Starting in November 2022, the XML feed will no longer support in-app purchases, subscriptions, metadata, or app pricing. You can manage this content via the App Store Connect REST API, which makes it easy to customize and automate your workflows.

The XML feed will continue to support existing Game Center management functionality.If you have any questions, contact us.

Best regards,
Apple Developer Relations
```

Do you know what I should update to not use this XML feed? Thank you!

**Comment by kirill-ivlev** [comment]
Hi @404pilot,
Thank you for your feedback! We will check this issue once we will have capacity.

**Comment by ismayilov-ismayil** [comment]
Hi @404pilot , thank you for reporting.
Actually, we use [fastlane](https://github.com/fastlane/fastlane) for AppStore release, and they use Rest Api to submit binaries via transporter. Thus, it doesn't impact to app-store-vsts-extension.

Closing this one, feel free to ask any other questions or let us know if it's still relevant for you.
