### ISSUE TITLE
No UI to specify AppSpecificPassword in AppStoreRelease@1 Task Release

### ISSUE THREAD

**Issue by vincentcastagna** [microsoft/app-store-vsts-extension#287]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question/Bug

**Enter Task Name**: AppStoreRelease@1

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks/AppStoreRelease

## Environment

- Agent -  Private: 
    

    - VS 2022 latest agent version

## Issue Description

Can't specify `AppSpecificPassword` in UI in ADO for the task, while we can specify it through yml. 

### Is it the right workaround then ? 
![image](https://user-images.githubusercontent.com/15191066/192636464-79093490-ab91-447a-ac39-476620f739d8.png)

https://ms-vsclient.gallerycdn.vsassets.io/extensions/ms-vsclient/app-store/1.207.0/1656509233572/images/release-task-with-advanced.png

It's not even specified in the doc

**Comment by vincentcastagna** [comment]
I can confirm that using Additional fastlane arguments works ... however could be great to have it such as AppSpecificId, directly in the UI.

**Comment by sergey-koryshev** [comment]
Hi @vincentcastagna, to let task `AppStoreRelease` set environment variable `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` you need to specify it in your service connection:
![image](https://user-images.githubusercontent.com/11807074/196196245-42d4ad37-4a39-4374-8d34-5254a1abe6c3.png)

Let me know if you have any questions

**Comment by sergey-koryshev** [comment]
Closing the issue as mitigated

@vincentcastagna, please feel free to reactivate it.
