### ISSUE TITLE
App store Promote fails

### ISSUE THREAD

**Issue by shilpa-maria** [microsoft/app-store-vsts-extension#297]
## Note  
Issues in this repo are for tracking bugs, feature requests and questions for the tasks in this repo 

For a list:  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Question

**Enter Task Name**: AppStoreRelease@1
[Yaml Pipeline deployment-ios.txt](https://github.com/microsoft/app-store-vsts-extension/files/10104515/Yaml.Pipeline.deployment-ios.txt)
[ios error log 28_11_22.txt](https://github.com/microsoft/app-store-vsts-extension/files/10104520/ios.error.log.28_11_22.txt)

list here (V# not needed):  
https://github.com/microsoft/app-store-vsts-extension/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?   Azure Pipelines
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private:  
    
    - If using Hosted agent, provide agent queue name:  Microsoft Hosted Agent : "macos-latest"

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

Issue: Promoting ios app from Testflight to production from Azure Yaml Pipeline using 'TASK: AppStoreRelease@1' fails.The app successfully gets deployed till TestFlight from Azure Pipeline. But fails on deploying to production.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

[Insert error from the logs here for a quick overview]

**Comment by max-zaytsev** [comment]
@shilpa-maria thanks for reporting the issue. 
When did it start to fail?
Could you please share pipeline logs from the lst successful run and the first failure?

**Comment by shilpa-maria** [comment]
Hi Maxim,

The task ***@***.*** never got successful. The task failed everytime it was used.
The latest pipeline run was made yesterday 29.11.2022, which also failed.


Thanks & Regards,
Shilpa Maria

**Comment by shilpa-maria** [comment]
Hi Maxim,

May I please have an update.

Thanks & Regards,
Shilpa Maria
From: Shilpa ***@***.***>
Sent: 29 November 2022 10:14
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [microsoft/app-store-vsts-extension] App store Promote fails (Issue #297)

Hi Maxim,

The task ***@***.*** never got successful. The task failed everytime it was used.
The latest pipeline run was made yesterday 29.11.2022, which also failed.


Thanks & Regards,
Shilpa Maria

**Comment by shilpa-maria** [comment]
Hi , Can I please have an help on this.

**Comment by Roman-Shchukin** [comment]
Hi @shilpa-maria. Could you please add '--verbose' as additional fastlane argument to get more info about error?

**Comment by shilpa-maria** [comment]
Hi Roman,

Since this can be tested only during production deploy , I won’t be able to  send the  –verbose logs at the moment.

Thanks & Regards,
Shilpa Maria

**Comment by Roman-Shchukin** [comment]
I suppose thi is the problem:
`/usr/local/lib/ruby/gems/3.0.0/gems/fastlane-2.211.0/deliver/lib/deliver/detect_values.rb:54:in 'find_app': [!] undefined method 'team_id' for nil:NilClass (NoMethodError)`
Could you revise $(team-id) variable?

**Comment by shilpa-maria** [comment]
Hi Roman,

Rechecked team-id value. The value passed is correct.
Now we have modified the app-identifier(bundle Id) value. Based on it , please find the attached new logs received.
Can you please check the issue with the attached logs.

Thanks & Regards,
Shilpa Maria

**Comment by Roman-Shchukin** [comment]
Now the error in logs from faslane is:
```
2022-12-12T05:52:26.7768490Z [!] Use of Advertising Identifier (IDFA) is required to submit
2022-12-12T05:52:26.7769380Z Add information to the :submission_information option...
2022-12-12T05:52:26.7770360Z   Docs: http://docs.fastlane.tools/actions/deliver/#compliance-and-idfa-settings
2022-12-12T05:52:26.7771020Z   Example: submission_information: { add_id_info_uses_idfa: false }
2022-12-12T05:52:26.7771520Z   Example: submission_information: {
2022-12-12T05:52:26.7772090Z     add_id_info_uses_idfa: true,
2022-12-12T05:52:26.7772510Z     add_id_info_serves_ads: false,
2022-12-12T05:52:26.7772930Z     add_id_info_tracks_install: true,
2022-12-12T05:52:26.7773440Z     add_id_info_tracks_action: true,
2022-12-12T05:52:26.7773870Z     add_id_info_limits_tracking: true
2022-12-12T05:52:26.7774220Z   }
```

**Comment by Roman-Shchukin** [comment]
Hi @shilpa-maria do you have any updates?

**Comment by Roman-Shchukin** [comment]
Hi @shilpa-maria closing this one - feel free to ask any other questions or let us know if it's still relevant for you.
