### ISSUE TITLE
Unable to release macOS pkg with TestFlight

### ISSUE THREAD

**Issue by duykhiem** [microsoft/app-store-vsts-extension#299]
## Issue Description
TestFlight is now supported macOS: https://testflight.apple.com/
But I can't release macOS pkg with TestFlight using the ```AppStoreRelease@1``` task on Azure Pipeline.

```
  - task: AppStoreRelease@1
    displayName: TestFlight macOS
    inputs:
      serviceEndpoint: 'AppStore-Connection'
      releaseTrack: 'TestFlight'
      appIdentifier: 'com.my.app'
      appType: 'macOS'
      ipaPath: '$(Build.ArtifactStagingDirectory)/*-signed.pkg'
      appSpecificId: 'xxxxxxxx1'
      shouldSkipWaitingForProcessing: true
      shouldSkipSubmission: true
      
[12:29:52]: Error setting value '/Users/runner/work/1/a/myapp-1.0-signed.pkg' for option 'ipa'

[!] '/Users/runner/work/1/a/myapp-1.0-signed.pkg' doesn't seem to be an ipa file
##[error]Error: The process '/usr/local/lib/ruby/gems/3.0.0/bin/fastlane' failed with exit code 1
Finishing: TestFlight macOS
```

```
  - task: AppStoreRelease@1
    displayName: TestFlight macOS
    inputs:
      serviceEndpoint: 'AppStore-Connection'
      releaseTrack: 'TestFlight'
      appIdentifier: 'com.my.app'
      appType: 'macOS'
      appSpecificId: 'xxxxxxxx1'
      shouldSkipWaitingForProcessing: true
      shouldSkipSubmission: true
      skipBinaryUpload: true
      fastlaneArguments: '--pkg "$(Build.ArtifactStagingDirectory)/Novus.NeXt.Gen-1.0-signed.pkg"'
      
##[error]Error: No IPA file found using pattern: /Users/runner/work/1/s/**/*.ipa
Finishing: TestFlight macOS
```

## Environment
- Server - Azure Pipelines
- Agent - Hosted macOS-12

## More info
Previous related PR : https://github.com/microsoft/app-store-vsts-extension/pull/117 (This change only for Production release track)
Previous related Issue: https://github.com/microsoft/app-store-vsts-extension/issues/158

**Comment by DenisRumyantsev** [comment]
@duykhiem thanks for reporting this issue.
We are currently working on higher-priority issues and we will work on this one as soon as we can

**Comment by vmapetr** [comment]
Related PR - https://github.com/microsoft/app-store-vsts-extension/pull/306. 
Kudos to @martinh2011 for the contribution.

**Comment by vmapetr** [comment]
The fix was merged in the master branch and will be available with the next release.

**Comment by DevEddy** [comment]
I also getting this issue, when ca

**Comment by vmapetr** [comment]
@DevEddy version 1.218.0 now is available on the marketplace - https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store

**Comment by DevEddy** [comment]
Hey @vmapetr thank you, I can confirm the fix.
