### ISSUE TITLE
Why Bundle ID is a required parameter?

### ISSUE THREAD

**Issue by evnik** [Microsoft/app-store-vsts-extension#30]
I use the _App Store Release_ task to publish several apps to the TestFlight from a single repository. To achieve that I have a script, which applies the bundle identifier to `Info.plist` file before build. My previous upload script didn't use the bundle identifier, because fastlane can take it right from the package. Additionally, according to the [source code](https://github.com/Microsoft/app-store-vsts-extension/blob/master/Tasks/app-store-release/app-store-release.ts#L97), the `Bundle ID` parameter is used only in case the `Track` is set to _Production_. So, what is the reason to make it required independently on the `Track` value?

As a workaround, I've filled it with some value, and that works, because the value isn't used.

**Comment by madhurig** [comment]
@evnik: Will address in the next update. Thank you.
