### ISSUE TITLE
Confused with release option

### ISSUE THREAD

**Issue by maitines** [Microsoft/app-store-vsts-extension#31]
I created a build that compiles, I installed the release extension, but when I go to configure it, in the binary path the IPA file isn’t there. Do I need to configure something else?

Attached are two images one of each section:

![build](https://cloud.githubusercontent.com/assets/3152931/18432326/a96e3156-78e1-11e6-886f-a9cedaecc970.png)
![release](https://cloud.githubusercontent.com/assets/3152931/18432325/a96a1da0-78e1-11e6-8dba-c2ffee5b9ba4.png)

**Comment by madhurig** [comment]
@maitines: In your build you need to upload the build artifacts, so the release can access them. You can do the using the "Copy Files" and "Publish Build Artifacts" task which are built in. In my build definition I copy the files I need to the staging folder and then upload them to the server. You can try something like this in your build definition:
![copyfiles](https://cloud.githubusercontent.com/assets/3269636/18635248/61d5617c-7e52-11e6-9fe5-5613a22b090d.png)
![publish](https://cloud.githubusercontent.com/assets/3269636/18635260/6ab3ec32-7e52-11e6-8b75-4e2d5c58ff51.png)

Hope this helps.

Thanks,
Madhuri

**Comment by madhurig** [comment]
@maitines: Let me know if this is still an issue for you. If you have a problem, please email your build log from where you are uploading the artifacts to me madhurig at Microsoft dot com. Thanks!
