### ISSUE TITLE
Submit for review requires submission information

### ISSUE THREAD

**Issue by zurdev** [Microsoft/app-store-vsts-extension#32]
When submit for review option is selected in Publish task, the flag "--submit_for review true" is passed to deliver tool. However, this is insufficient, and the app will not be submitted for review. See this [issue](https://github.com/fastlane/fastlane/issues/4431) for example.
The user should also provide the [submission information](https://github.com/fastlane/fastlane/blob/master/deliver/Deliverfile.md#submission_information), for automating this step.

**Comment by madhurig** [comment]
@zurdev: I didn't need to do this to submit my app. But I had set these in iTunes Connect one time. Have you run into this even after setting these up in iTunes Connect for subsequent submissions?

**Comment by lkillgore** [comment]
Hi @zurdev.  As far as I can tell, this works if the submission information is sent via metadata.  I'm going to close this issue.  If this is still not working for you, could you please open another issue so we can either fix the issue or help you work through the problem? Thanks!
