### ISSUE TITLE
Unable to publish iOS app to beta external groups in testflight

### ISSUE THREAD

**Issue by arpitmishra-eaton** [microsoft/app-store-vsts-extension#337]
Hi Team - we are publishing an app to Testflight channel (external groups) from Azure pipelines and receiving an error "Error: 'What to Test?' is required when using 'Distribute to External Testers'."

Here is my yml script. 

  - task: AppStoreRelease@1
              inputs:
                authType: 'ApiKey'
                apiKeyId: $(API-key-id)
                apiKeyIssuerId: $(Issuer ID)
                apitoken: $(authkey64)
                releaseTrack: 'TestFlight'
                appIdentifier: 'com.eaton.abc'
                appType: 'iOS'
                releaseNotes: '$(System.DefaultWorkingDirectory)/releaseNotes.txt' 
                ipaPath: '$(build.artifactstagingdirectory)/**/*.ipa'
                distributedToExternalTesters: true
                externalTestersGroups: 'abc groups'
                appSpecificId: '123'

Please help me with this. what needs to be configured in the release notes option?
```[tasklist]
### Tasks
```

**Comment by arpitmishra-eaton** [comment]
i checked with raw text as well but it didn't work either.

**Comment by aleksandrlevochkin** [comment]
@arpitmishra-eaton this looks like a duplicate of https://github.com/microsoft/app-store-vsts-extension/issues/338. Can we close it?

**Comment by arpitmishra-eaton** [comment]
sure.
