### ISSUE TITLE
Question: Basic functionality, quick start instructions

### ISSUE THREAD

**Issue by sirnameless** [microsoft/app-store-vsts-extension#363]
Does this extension build the app and upload from hosted Azure? Or does it just kick off a build from a local Mac? (Basically, does all the magic happen in the cloud? ☁️❗ )

Thanks!

**Comment by vmapetr** [comment]
Hi @sirnameless, thank you for your question!

Basically, this extension contains a set of new deployment tasks which allows you to connect your CI environment to the Apple's App Store. Execution of these tasks is not different from any other in-box ADO task, they can be queued on the MS-hosted agents which are deployed in the cloud, or they can be queued on your local machine, or your VM set in the Azure. 
Please check more information about the difference between agents in this [documentation](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?).

To configure the strategy of your pipeline, use the [pool](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pool?view=azure-pipelines)definition in the YAML template, and ADO choses the environment that was specified in this definition, e.g. if you decide to use self-hosted agent, you need to [create custom pool](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=yaml%2Cbrowser) for your organization, prepare the environment on the selected machine, connect it to the pool, and specify this pool in the template like this:
```
pool: MyPoolName
```
In case if you want to use MS-hosted agents you can simply choose required VM image like this:
```
pool:
  vmImage: macos-latest
``` 
With this configuration, ADO will create the temporary machine from selected image, with environment configured accordingly to specification mentioned in this repo - https://github.com/actions/runner-images, that will exist only during the pipeline execution, and deallocated right after pipeline completion.

For more information about ADO extensions please check following [documentation](https://learn.microsoft.com/en-us/azure/devops/extend/overview?view=azure-devops).

**Comment by sirnameless** [comment]
Fantastic, thank you. That helps a lot!

**Comment by vmapetr** [comment]
@sirnameless Glad I could help!
I'm going to close this ticket, but please feel free to reopen it if you have additional questions.
