### ISSUE TITLE
Could not find a version to edit for app 'App Name', the app metadata is read-only currently

### ISSUE THREAD

**Issue by brucewilkins** [Microsoft/app-store-vsts-extension#38]
The publish to the App Store Production task is failing with the following error:
`Could not find a version to edit for app 'App Name', the app metadata is read-only currently`

The task is configured to upload metadata, screenshots and submit for review.

In iTunes Connect the app has an existing version with the status 'Ready for Sale'. I expect the fastlane delivery process to create a new version matching the version of the ipa file.

It appears to be similar to [this issue](https://github.com/fastlane/fastlane/issues/2210), however the version of deliver by the extension is 1.14.0.

Please advise as its not an option to have to manually create the version in iTC for each deployment.

[releaselog.zip](https://github.com/Microsoft/app-store-vsts-extension/files/495397/releaselog.zip)

**Comment by madhurig** [comment]
@brucewilkins: It looks like you are running into this issue: https://github.com/fastlane/fastlane/issues/1517 and you would need to pass "--app_version" to deliver. But we don't support passing in additional arguments to the task currently. I will add this for the next update. If you don't want to do this manually, you can try scripting this with a shell script that you can use in your release definition.

**Comment by brucewilkins** [comment]
@madhurig, thanks for the info! Is there an ETA on the next update?

**Comment by madhurig** [comment]
@brucewilkins: I am investigating further today. If I allow passing in custom arguments, you will need to manually pass the --app_version in to your build/release. Is that acceptable or are you expecting automatically detecting the version and passing it in?

**Comment by brucewilkins** [comment]
@madhurig the version number is available as a variable during the build, but I don't think its available during the release in VSTS. So we would need the version to be determined from the package.

**Comment by madhurig** [comment]
We haven't been able to repro this with older versions and the latest version of fastlane, so closing this issue. If you continue to have issues, please let us know.

Thanks,
Madhuri
