### ISSUE TITLE
Support for Wildcards in Binary Path 

### ISSUE THREAD

**Issue by deekob** [Microsoft/app-store-vsts-extension#40]
Hi,
Is there any chance to include support for wildcards in the Binary Path field for App Store Release Task.

Example
$(build.artifactstagingdirectory)/*_/_.ipa - just doesnt work as I get the following error

Could not find ipa file at path '_work/3/a/*_/_.ipa even though there is one .ipa present that satisfies this.

Specifying the ipa file name yields the same result.

Thanks

**Comment by iMacX** [comment]
Same demand here. Did you find a solution? thx

**Comment by rusty21** [comment]
This would be nice. The google play version of this build step supports wildcards.

**Comment by deekob** [comment]
Awesome - thx!
