### ISSUE TITLE
Can't deploy from Release tasks.

### ISSUE THREAD

**Issue by kstoj** [Microsoft/app-store-vsts-extension#42]
Trying to deploy the iOS Xamarin application build with MS Visual Studio.  The Deploy task comes back with an error: "App store promote can only be run from a Mac computer." The task is to Publish to the "TestFlight" track, not promote to AppStore.

**Comment by DavidStaheli** [comment]
Thanks for reporting this, @kstoj.  It is fixed with pull request #43 and will be released shortly.  The changes will be automatically received by your installation once the release happens.
