### ISSUE TITLE
Uploading to iTunes connect never completes

### ISSUE THREAD

**Issue by epopov** [Microsoft/app-store-vsts-extension#44]
I tried different options to deploy new build: Production, TestFlight but they all time out and never complete. Here is the last log lines:
: Uploading binary to iTunes Connect
: Going to upload updated app to iTunes Connect
: [32mThis might take a few minutes. Please don't interrupt the script.[0m

How can I troubleshoot the issue? I am using macincloud VSTS agent to run the build.

**Comment by epopov** [comment]
Hey @ryuyu any ideas what is could be?

**Comment by ryuyu** [comment]
Hmm. At first glance, it looks like there might be a connection issue between the agent and the apple servers.

This task runs a series of fastlane tasks, so what you can try is to run the fastlane tasks that it does locally (or from the build machine if you have access to remote) and see if you can reproduce the failure.

I believe that the TestFlight track runs "pilot upload -u [user] -i [ipaPath]" in the simplest case, and Production runs "deliver --force -u [user] -a [bundleId] -i [ipaPath]". If these succeed locally, it is likely a problem with the connection from the MiC agent to the Apple servers. If the problem repros in this case, there may be a problem with the latest version of Fastlane.

@madhurig can maybe give you some more information here.

**Comment by epopov** [comment]
I don't have access to the agent. It's macincloud VSTS agent. Re there any
special parameters that I can add to VSTS task to get detail error log?

**Comment by ryuyu** [comment]
Setting the system.debug variable in your build to true might add some more output, but it looks like the task is stalling after we shell out to fastlane, so I'm not sure it will give us anything actionable.

**Comment by epopov** [comment]
Forgot to tell, that it worked fine before.

**Comment by epopov** [comment]
Forgot to tell that it worked fine before. And what I noticed it shows
warning about outdated version of the ship or some thing like that. Where
should I update it? On agent or on your side?

**Comment by madhurig** [comment]
Can you share the log which shows the outdated version, so I can verify what needs update? I am wondering if you are running into some firewall issues on the MacinCloud agent: https://github.com/fastlane/fastlane/tree/master/deliver#firewall-issues

**Comment by epopov** [comment]
You're using an old version of spaceship

2016-11-25T14:23:45.6984940Z To ensure spaceship and fastlane works

2016-11-25T14:23:45.7007880Z update to the latest version.

2016-11-25T14:23:45.7019430Z

2016-11-25T14:23:45.7042020Z Run `[sudo] gem update spaceship`

2016-11-25T14:23:45.7053900Z

2016-11-25T14:23:45.7076760Z or `bundle update` if you use bundler.

2016-11-25T14:23:45.7088540Z

2016-11-25T14:23:45.7112590Z [33mYou're on spaceship version: 0.37.0[0m

2016-11-25T14:23:45.7137360Z [33mLatest spaceship version : 0.38.0[0m

2016-11-25T14:23:45.7149830Z

**Comment by epopov** [comment]
Any thoughts? @madhurig

**Comment by madhurig** [comment]
@epopov: The task should be updating the fastlane tools before attempting to upload the IPA. In my build log I see this even when I run on my MacinCloud VSTS server:
2016-11-30T20:25:46.0037030Z [command]/usr/bin/gem install deliver
2016-11-30T20:26:08.9819210Z Successfully installed credentials_manager-0.16.2
2016-11-30T20:26:08.9832250Z Successfully installed fastlane_core-0.57.2
2016-11-30T20:26:08.9844000Z Successfully installed spaceship-0.38.4
2016-11-30T20:26:08.9854630Z Successfully installed deliver-1.16.0

Can you share your full log? You can either upload it here or email me: madhurig at Microsoft dot com. 

Thanks,
Madhuri

**Comment by ryuyu** [comment]
@madhurig It seems we might need to have some logic to clear cache.
In your log, it successfully installs spaceship-0.38.4, which is actually the old version; it needs to be installing spaceship-0.38.5.
Gem install doesn't seem to do update.
What we can probably do is call gem update after install, but this will add time to build unless the update call is very short.

**Comment by madhurig** [comment]
@ryuyu: @jeffyoung and I are considering the best way to do it without unnecessarily adding to the build time. We will likely introduce an advanced option on the task to clear the cache.

**Comment by iMacX** [comment]
Hi,

I was using VSTS plugin 

https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store

to upload to testflight successfully but since quite recently, I get this message and process seems to be stocked on "This might take a few minutes. Please don't interrupt the script."

> Successfully installed fastlane-2.9.0
-Please use `fastlane pilot` instead of `pilot` from now on.
Successfully installed pilot-2.0.0
pilot upload -u ******** -i /Users/developer/vsts/iOSapp.ipa -q 123456
/Users/developer/.gem-cache/gems/pilot-2.0.0/lib/pilot/version.rb:3: warning: already initialized constant Pilot::DESCRIPTION
/Users/developer/.gem-cache/gems/fastlane-2.9.0/pilot/lib/pilot.rb:21: warning: previous definition of DESCRIPTION was here
You are calling pilot directly. Usage of the tool name without the `fastlane` prefix is deprecated in fastlane 2.0
Please update your scripts to use `fastlane pilot upload -u ******** -i /Users/developer/vsts/iOSapp.ipa -q 123456` instead.
: Login to iTunes Connect (********)
: Login successful
: Ready to upload new build to TestFlight (App: 56789101112)...
: Going to upload updated app to iTunes Connect
: This might take a few minutes. Please don't interrupt the script.

**Comment by jeffyoung** [comment]
We are now always using the latest fastlane tools in the [1.112.0](https://github.com/Microsoft/app-store-vsts-extension/releases/tag/v1.112.0) release of the extension.  It is expected that issues like these will be addressed with the latest tools.  If not, please open a new issue.
