### ISSUE TITLE
Spaceship to be updated to be compatible with latest changes on iTunes Connect

### ISSUE THREAD

**Issue by Jossif** [Microsoft/app-store-vsts-extension#45]
https://github.com/fastlane/fastlane/releases/tag/spaceship%2F0.38.5

spaceship/0.38.5: Update spaceship to work with the new iTunes Connect

@KrauseFx KrauseFx tagged this 14 hours ago · 20 commits to master since this tag

- Update spaceship to work with the new iTunes Connect
- Update Gemfile setup to use local copy by default
- Improved docs

https://github.com/fastlane-old/spaceship/releases/tag/0.38.5

**Comment by Jossif** [comment]
Result of this is that the current version of extension is failing to upload the binary:

Z [31m---------------------------------------------[0m
 
2016-12-05T19:08:35.3202280Z [31m-------------------WARNING-------------------[0m
 
2016-12-05T19:08:35.3221110Z [31m---------------------------------------------[0m
 
2016-12-05T19:08:35.3238970Z You're using an old version of spaceship
 
2016-12-05T19:08:35.3254160Z To ensure spaceship and fastlane works
 
2016-12-05T19:08:35.3266990Z update to the latest version.
 
2016-12-05T19:08:35.3273570Z 
 
2016-12-05T19:08:35.3286270Z Run `[sudo] gem update spaceship`
 
2016-12-05T19:08:35.3292820Z 
 
2016-12-05T19:08:35.3305580Z or `bundle update` if you use bundler.

**Comment by ryuyu** [comment]
Hmm.
The task should be running a gem install of the pilot/deliver tools when it runs.
It seems that it might be picking up a cached version from a previous run and not installing the new version.
To see if this clears up, can you clear the gem cache on your build machine and run the task again and see if it works/picks up the latest versions?

@madhurig It seems we might need some cache busting logic if this is the case.

**Comment by lawrencegripper** [comment]
Hi, 

Experiencing the same issue. 

Just run "sudo gem source -c" on the build machine and waiting to see if the build now behaves, will update if that does the trick.

**Comment by lawrencegripper** [comment]
Right, found a fix!

Looking at the code it's using the users home dir /.gem-cache as the cache location so I went and deleted that folder and all is well. 

For example:

cd /usrs/username
rm -rf .gem-cache

**Comment by Jossif** [comment]
That helped, thank you.
