### ISSUE TITLE
feature request: add ability to push testflight build to exernal testers

### ISSUE THREAD

**Issue by Jossif** [Microsoft/app-store-vsts-extension#48]
Please add the option to enable distribute_external in order to push the build to external testers

FastlaneCore::ConfigItem.new(key: :distribute_external,
                                     is_string: false,
                                     env_name: "PILOT_DISTRIBUTE_EXTERNAL",
                                     description: "Should the build be distributed to external testers?",
                                     default_value: false),

from https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/options.rb

Should appear only when Track=TestFlight in App Store Release task

**Comment by lkillgore** [comment]
Hi, @Jossif!  We added this feature in the latest release of the extension.  Thank you for the suggestion!
