### ISSUE TITLE
Could not retrieve response as fastlane runs in non-interactive mode

### ISSUE THREAD

**Issue by r-win** [Microsoft/app-store-vsts-extension#51]
When publishing to the AppStore in TestFlight track, the pilot application asks for input about the bundleIdentifier, even though it's filled out in the settings.

> 2016-12-08T20:48:17.0687030Z [21:48:17]: Login to iTunes Connect (********)
> 2016-12-08T20:48:20.4899490Z [21:48:20]: Login successful
> 2016-12-08T20:48:20.5890610Z [21:48:20]: Please enter the app's bundle identifier:  

This was using vsts-agent 2.11.0, and app-store extension 1.2.1. Pilot version is 1.12.1.

For now, I've solved the problem by editing app-store-release.js, and supplying the bundleIdentifier in TestFlight mode as well (not only in Production).

**Comment by jeffyoung** [comment]
Do you have any more information (or insight) about why you believe this occurred?  Before we updated the extension to 1.2.1, we weren't actually sending the bundle identifier to pilot for the TestFlight track.  In 1.2.1, I made it optional for entry (in the textbox) but required for _Production_.

My first thought here was to add an option to _also_ send it to TestFlight but after checking our internal test build definition, we're able to successfully publish our IPA to TestFlight without providing the build identifier.  :-/ (That said, our internal test build is now using pilot 2.0.0 so perhaps a change was made in pilot between 1.12.1 and 2.0.0?)

So I'm trying to understand a bit more about what's going sideways here.  Additionally, once we publish the next version of the extension, you private fix is likely to get overwritten (and cause your builds to fail again).  And if I can prevent that from happening, I'd like to.

**Comment by KrauseFx** [comment]
A note from _fastlane_: _fastlane_ tries to automatically detect the bundle identifier based on the ipa file you provide.

**Comment by jeffyoung** [comment]
@KrauseFx: If the bundleId is sent via pilot for *both* TestFlight and Production, I assume pilot will use that value instead of trying to automatically detect it?  Is that a proper assumption?  If so, we may just require it for Production (and send it).  If the track is TestFlight, and bundleId is set, we'll send it there too.  (But if it's TestFlight and not set, we'll allow fastlane to detect it.)

**Comment by KrauseFx** [comment]
Mh, from Apple's side there is no difference between TestFlight and production, it's the exact same procedure, however you promote a build to an App Store build if necessary.

**Comment by lkillgore** [comment]
@r-win: we made an adjustment in the extension to send the bundle identifier for Test Flight builds when it's specified.  I think this should fix the behavior that you're seeing.  If you're still running into issues after using the latest version of the extension (v1.116.0), could you please let me know?
