### ISSUE TITLE
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

### ISSUE THREAD

**Issue by tobber72** [Microsoft/app-store-vsts-extension#58]
We get the following error when we run the app-store-vsts-extension "The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.". 

On the following page (https://github.com/fastlane/fastlane/blob/master/deliver/README.md#firewall-issues) it says that you can solve this error by typing "DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" fastlane upload...". (When we run this command manually from the terminal it works to upload the .ipa file to Appstore.)  

Is it possible to run "DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS..." via the app-store-vsts-extension in some way?

We use Apple App Store Release Version 1.112.0 and Fastlane version 2.14.2

**Comment by AlexRukhlin** [comment]
Hi,
You may define this variable in the "Variables" tab of your build definition.

Please see[Firewall issue](https://github.com/Microsoft/app-store-vsts-extension#firewall-issues) chapter on the main page of this repository for details.

Alex

**Comment by tobber72** [comment]
Fantastic, now it works! I have completely missed the "Firewall Issues chapter", thank you very much!
