### ISSUE TITLE
Upload to store fails when TeamID is set

### ISSUE THREAD

**Issue by zurdev** [Microsoft/app-store-vsts-extension#62]
This looks like a regression caused by a change to fastlane deliver tool.
When TeamID input is set, the extension passes argument '-q <teamid>' to fastlane deliver, which results in: Error setting value 'teamid' for option 'apple_watch_app_icon'
Removing the value of TeamID from publish task resolved the issue.

**Comment by jeffyoung** [comment]
Hi @zurdev.  While it does look like it's a bug in the fastlane tools, it's actually a bug in our tasks.  :-/  

Whenever we call deliver, we're setting the corresponding arguments for _pilot_ instead:
https://github.com/Microsoft/app-store-vsts-extension/blob/master/Tasks/app-store-release/app-store-release.ts#L160-L161
https://github.com/Microsoft/app-store-vsts-extension/blob/master/Tasks/app-store-promote/app-store-promote.ts#L106-L107

I'll get a fix out on this soon.  I'm glad you've got a workaround for now.
