### ISSUE TITLE
App Store Release build step does not show in the Deploy category list

### ISSUE THREAD

**Issue by budimartoyo** [Microsoft/app-store-vsts-extension#64]
Any possible reasons why my App Store Release or App Store Promote build steps don not show in the Deploy build steps? I have installed the extension in on premise TFS 2015 (v14.95.25122.0), and have a mac machine build agent registered.
App Store End Point Service has been added and the same user /group are registered.
Am I missing something?

Thanks

**Comment by madhurig** [comment]
The extension is supported and tested against TFS 2015 Update 3. The tasks show up and work as expected on TFS 2015 Update 3. 

I can repro the issue on TFS 2015 Update 2 (which is your TFS server version). Unfortunately, we don't have a workaround other than upgrading to TFS 2015 Update 3. 

Thanks,
Madhuri

**Comment by budimartoyo** [comment]
Thank you Madhuri,

I will upgrade my TFS into Update 3.
Cheers

**Comment by budimartoyo** [comment]
After upgraded to Update 3, the extension show up as expected.
Thank you.

Arif
