### ISSUE TITLE
New TestFlight release requires pilot changes

### ISSUE THREAD

**Issue by KrauseFx** [Microsoft/app-store-vsts-extension#68]
Hey everyone 👋

Felix here, from the _fastlane_ team, we're busy working on migration fastlane pilot to work with the new TestFlight, you follow along the progress over here: https://github.com/fastlane/fastlane/pull/8871

For any contributors to the `app-store-vsts-extension`, feel free to send me your email address, so we can add you to the contributor slack of fastlane 👍

**Comment by KrauseFx** [comment]
Feel free to close this issue of course

**Comment by DavidStaheli** [comment]
Thanks, @KrauseFx!
