### ISSUE TITLE
Add support for multiple iTunes providers.

### ISSUE THREAD

**Issue by skos-ninja** [Microsoft/app-store-vsts-extension#69]
Currently if your iTunes account is linked to multiple developer accounts you get an error saying: 
"Your Apple ID account is attached to other iTunes providers. You will need to specify which provider you intend to submit content to by using the -itc_provider command. Please contact us if you have questions or need help." 

Which stops you being able to submit apps using that itunes account.

This was fixed in fastlane here: [https://github.com/fastlane/fastlane/issues/1524](https://github.com/fastlane/fastlane/issues/1524) but now requires an option in the interface to be able to pass this parameter.

**Comment by jeffyoung** [comment]
Thanks for reporting @skos-ninja.  I'll mark this as an enhancement (to either ocnsidering adding that as a first class option on the task(s) or to provide an ability to add additional command line arguments freeform).

**Comment by madhurig** [comment]
For cases like this, I am adding a "fastlane arguments" input on the upload task: https://github.com/Microsoft/app-store-vsts-extension/pull/80.

**Comment by madhurig** [comment]
We have added the ability to pass in additional fastlane arguments for advanced scenarios like this in version 1.126.0.

Thanks,
Madhuri
