### ISSUE TITLE
Not able to push testflight build to exernal testers

### ISSUE THREAD

**Issue by praga** [Microsoft/app-store-vsts-extension#70]
I am getting the below error message when I tick the Distribute to External Testers, I cant seem to add groups as there is no such field.

`2017-05-26T08:14:00.7533170Z [!] You must specify at least one group using the `:groups` option to distribute externally
2017-05-26T08:14:01.1840610Z ##[error]Error: fastlane failed with return code: 1`

**Comment by madhurig** [comment]
@praga: Do you still have this issue? please try updating fastlane on your deployment machine by running "gem update fastlane" manually or using the option in the "Advanced" section of the task to update fastlane. 
#71 seems to be the same issue.

Thanks,
Madhuri

**Comment by grubstarstar** [comment]
I just got this with a fresh install of fastlane today.

**Comment by jpricketMSFT** [comment]
We have this on our backlog and will be working on it soon.

**Comment by grubstarstar** [comment]
@jpricketMSFT that's awesome thanks!

**Comment by grubstarstar** [comment]
@jpricketMSFT is this the best issue to subscribe to to find out when it's done?

**Comment by jpricketMSFT** [comment]
@grubstarstar - I think so. The changes will be in this repo and we will close the issue when the fix goes in. However, it will take some time for the fix to flow through our release process. I don't know how long that will take. But it shouldn't be too long.

**Comment by madhurig** [comment]
@grubstarstar : Yes, this issue is the right place to watch. We close issues when we release a new version of the extension is released and available for use. Thanks!

**Comment by madhurig** [comment]
Fixed with latest release, please let us know if you still see issues. 

Thanks,
Madhuri
