### ISSUE TITLE
Cannot Promote App from Test Flight to App Store

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/app-store-vsts-extension#72]
I am trying to use the Promote part of the extension but it throws the following error:

> You must detail what's new in this version in English (U.K.).

There is no way to provide this information in the Extension so there is no way this can work

**Comment by lkillgore** [comment]
Hi @JKennedy24, I've personally seen that error before, though not in the place you're describing.  Could you please double-check something for me?   IIRC, I saw that error in the Release task using 'Distribute to External Testers' option without setting the release notes.

(Basically, I didn't follow this tooltip)
![image](https://user-images.githubusercontent.com/26548919/26948137-4841d346-4c63-11e7-86f5-34a990ed1dc7.png)

Could you please see if you're sending the release notes in this step under "What to Test?"?

**Comment by JKennedy24** [comment]
Hi Ikillgore. Some more information. I am using the following tasks for release builds as so

- Upload to Test flight (provided release notes and ticked distribute to external testers)
  failed with this message [https://github.com/Microsoft/app-store-vsts-extension/issues/71](https://github.com/Microsoft/app-store-vsts-extension/issues/71)
I then manually distributed to external testers through itunes connect and ran...

- Promote testflight to release 
this step then failed with message outlined in this issue.

Does that sound plausible? The error in releasing testflight to external testers could have a knock on affect and cause this error?

**Comment by lkillgore** [comment]
Short answer: yes, it sounds plausible.

Do you know if you can promote manually w/o having the release notes set?

**Comment by JKennedy24** [comment]
I don't think you need release notes to promote applications. But I am not 100% sure. I will have to test this out with the attribute from #71 next release cycle

**Comment by JKennedy24** [comment]
This now works after adding the attribute mentioned in #71. Thanks
