### ISSUE TITLE
fastlane failed with return code: 1

### ISSUE THREAD

**Issue by ahmedAlmasri** [Microsoft/app-store-vsts-extension#74]
couldn't find app 'item/details' on the account of '********' on iTunes Connect
error]Error: fastlane failed with return code: 1

**Comment by madhurig** [comment]
@ahmedAlmasri: Were you able to get past this error? It seems like some input was not specified like the bundle ID which identifies the app.

**Comment by madhurig** [comment]
@ahmedAlmasri: Closing since we don't have details. Let us know if you are running into issues with the latest version of the extension.

Thanks,
Madhuri
