### ISSUE TITLE
What to test parameter doesn't seem to work

### ISSUE THREAD

**Issue by lukewis** [microsoft/app-store-vsts-extension#77]
This seems related to #47, but I can't seem to get the "What to test" feature to work correctly.  No matter what string I specify, the "What to test" field in Testflight remains blank.  Are there any "special considerations" for using this feature that I should be aware of?

**Comment by madhurig** [comment]
@lukewis: I can see the "What to test" field populated with the data I pass in to the task when uploading to "TestFlight". Do you have multiple languages that your app ships in? Please share relevant portion of the logs from your build, particularly the fastlane commands being run if you still have this issue.

Thanks,
Madhuri

**Comment by lukewis** [comment]
Hi @madhurig, after reviewing some of my logs, I'm wondering if the reason I never saw this field populated is because I had checked the "don't wait for processing to complete" option.  Is waiting for processing to complete required for this feature to work?

**Comment by lukewis** [comment]
I tried this again today and made sure I UN-checked the "skip waiting for processing" option and things worked as expected.  It might be nice to add a blurb in the "info tips" for both What to Test and Skip waiting for processing to indicate that those options are mutually exclusive.

**Comment by madhurig** [comment]
@lukewis: Thank you, we will update the documentation.
