### ISSUE TITLE
Cannot release to Alpha

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/app-store-vsts-extension#79]
So I have been using this build task to release my app to alpha then promote to stable. It has worked in the past. - Last ran it about 2 weeks ago.

Went to run it today and got this error:

> 2017-10-10T15:20:57.5478730Z ERROR:  Could not find a valid gem 'fastlane' (>= 0), here is why:
> 2017-10-10T15:20:57.5516210Z           Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/latest_specs.4.8.gz)
> 2017-10-10T15:21:01.3339600Z ERROR:  Possible alternatives: fastlane

**Comment by yacaovsnc** [comment]
This looks like a network issue.  Are you using a private agent? If you run this job again, do you still experience this issue?

**Comment by JKennedy24** [comment]
@yacaovsnc I am using a private agent.

I have ran it again and it has succeeded this time. Thanks for your help. I will close this issue

**Comment by yacaovsnc** [comment]
Glad it worked.
