### ISSUE TITLE
Install fastlane option results in failure due to permissions issue

### ISSUE THREAD

**Issue by kaclark28** [Microsoft/app-store-vsts-extension#87]
When running the 'Ipa Resign' task using the "Install fastlane" option I'm getting the following error:
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.75.1/LICENSE

This is occurring on the Hosted macOS Preview Agent queue.

**Comment by madhurig** [comment]
@kaclark28 : What version of fastlane are you trying to install with the task? Installing the latest version is working on the hosted macOS preview agents.

**Comment by kaclark28** [comment]
@madhurig I was installing the latest version of fastlane which happened to be version 2.75.1 when I submitted the ticket. I just tried it again, and it succeeded (it looks like the current version of fastlane is now 2.77.1) so it looks like it must have been an issue with that particular version of fastlane. I'll close the issue as it appears resolved now. Thanks for the help!
