### ISSUE TITLE
tvOS provisioning profile is not compatible with iOS apps

### ISSUE THREAD

**Issue by shoshins** [Microsoft/app-store-vsts-extension#96]
Trying to upload tvOS application to testflight using this App store extension. Tfs generates code like this: 
`fastlane pilot upload -u ******** -i /path/to/release/application.ipa --changelog "Improvements" -a bundle.id --distribute_external true --groups testers`

I have exacly the same build for iOS and it works fine. But tvOS platform cannot be published, because of error:

> ERROR ITMS-90545: "Invalid Provisioning Profile. This provisioning profile is not compatible with iOS apps."
2018-07-21T08:29:49.3702670Z Return status of iTunes Transporter was 1: ERROR ITMS-90545: "Invalid Provisioning Profile. This provisioning profile is not compatible with iOS apps."
2018-07-21T08:29:49.3734530Z The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

I read about it and found that `--app_platform "appletvos"` should be passed to fix that.

I passed this parameter to "Additional fastlane arguments", but now tfs says: 
> invalid option: --app_platform appletvos

To be sure that it is right parameter I tried to run this command with it directly in terminal on the agent machine. And the command generated by tfs with this parameter works in terminal. It broken only in tfs.
`fastlane pilot upload -u ******** -i /path/to/release/application.ipa --changelog "Improvements" -a bundle.id --distribute_external true --groups testers --app_platform appletvos`

To be sure that I use "Additional fastlane arguments" in right way i tried to pass "--verbose" parameter. It works without errors like 'invalid option'

What's wrong?

**Comment by shoshins** [comment]
fixed. I just set "Additional fastlane arguments" to `--app_platform=appletvos`. It will be better to present example for text inputs like this one.

**Comment by WrRaThY** [comment]
thanks for that, it solved it for me.
just for future reference I'm putting the `Fastfile` version of it:
```
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      app_platform: "appletvos"
    )
```
